

-- Create tb_organization
CREATE TABLE tb_organization (
    OrgEin CHAR(9) PRIMARY KEY,
    OrgBusinessName VARCHAR(100),
    OrgStreet VARCHAR(50),
    OrgCity VARCHAR(30),
    OrgState CHAR(2) CONSTRAINT org_state_len_check CHECK (char_length(OrgState) = 2),
    OrgZip CHAR(5) CONSTRAINT org_zip_len_check CHECK (char_length(OrgZip) = 5),
    OrgWebsite VARCHAR(30),
    OrgFormationYr smallint,
    OrgMissionDisc text,
    OrgPhoneNumber CHAR(10) CONSTRAINT org_phone_len_check CHECK (char_length(OrgPhoneNumber) = 10),
    CreateDate timestamp,
    isUpdated boolean DEFAULT FALSE,
    UpdateDate timestamp,
    UpdateBy CHAR(3)
);


-- Create tb_officer_salary
CREATE TABLE tb_officer_salary (
    OrgEin CHAR(9) REFERENCES tb_organization (OrgEin),
    EmployeeId CHAR(14) GENERATED ALWAYS AS (lower(concat(substring(OrgEin from 6), substring(OfficerName for 3), substring(OfficerTitle for 3), TaxYr))) STORED,
    ReturnType VARCHAR(5) CONSTRAINT sal_return_type_len_check CHECK (char_length(ReturnType) = 3 OR char_length(ReturnType) = 5),
    TaxYr CHAR(4) CONSTRAINT sal_tax_yr_len_check CHECK (char_length(TaxYr) = 4),
    OfficerName VARCHAR(30),
    OfficerTitle VARCHAR(30),
    OfficerAvgHrsPerWeekRt decimal,
    OfficerAvgHrsPerWkDevotedToPosRt decimal,
    OfficerAvgHrsPerWeekRltdOrgRt decimal,
    OfficerCompAmt numeric,
    OfficerReportCompFromOrgAmt numeric,
    OfficerReportCompFromRltdOrgAmt numeric,
    OfficerOtherCompAmt numeric,
    OfficerEmplBenefitProgAmt numeric,
    OfficerExpnsAccntOtherAllwncAmt numeric,
    CreateDate timestamp,
    isUpdated boolean DEFAULT FALSE,
    UpdateDate timestamp,
    UpdateBy CHAR(3),
    PRIMARY KEY (OrgEin, OfficerName, TaxYr)
);


-- Create tb_990_return
CREATE TABLE tb_990_return (
    OrgEin CHAR(9) REFERENCES tb_organization (OrgEin),
    ObjectId VARCHAR(22),
    ReturnDate date,
    ReturnType VARCHAR(5) CONSTRAINT r990_return_type_len_check CHECK (char_length(ReturnType) = 3 OR char_length(ReturnType) = 5),
    TaxYr CHAR(4) CONSTRAINT r990_tax_yr_len_check CHECK (char_length(TaxYr) = 4),
    TotalEmployeeCnt smallint,
    GrossReceiptsAmt numeric,
    TotalGrossUBIAmt numeric,
    ContribGrantsAmt numeric,
    ProgramServiceRevAmt numeric,
    InvestIncomeAmt numeric,
    OtherRevAmt numeric,
    TotalRevAmt numeric,
    GrantsAndSimilarPaidAmt numeric,
    BenefitsPaidToMembersAmt numeric,
    SalariesCompEmpBnftPaidAmt numeric,
    TotalProfFndrsngExpnsAmt numeric,
    TotalFndrsngExpnsAmt numeric,
    OtherExpnsAmt numeric,
    TotalExpnsAmt numeric,
    RevLessExpnsAmt numeric,
    TotalAssetsBOYAmt numeric,
    TotalAssetsEOYAmt numeric,
    TotalLiabilitiesBOYAmt numeric,
    TotalLiabilitiesEOYAmt numeric,
    NetAssetsOrFundBalancesBOYAmt numeric,
    NetAssetsOrFundBalancesEOYAmt numeric,
    ExpnsAmt numeric,
    GrantAmt numeric,
    RevAmt numeric,
    TotalOtherProgSrvcExpnsAmt numeric,
    TotalOtherProgSrvcGrantAmt numeric,
    TotalOtherProgSrvcRevAmt numeric,
    TotalProgramSrvcExpnsAmt numeric,
    TotalReportableCompFromOrgAmt numeric,
    TotalReportableCompRltdOrgAmt numeric,
    TotalOtherCompAmt numeric,
    FederatedCampaignsAmt numeric,
    MembershipDuesAmt numeric,
    FundraisingAmt numeric,
    RelatedOrgAmt numeric,
    GovGrantsAmt numeric,
    AllOtherContrAmt numeric,
    NonCashContrAmt numeric,
    TotalContrAmt numeric,
    CreateDate timestamp,
    isUpdated boolean DEFAULT FALSE,
    UpdateDate timestamp,
    UpdateBy CHAR(3),
    PRIMARY KEY (OrgEin, ObjectId, TaxYr)
);


-- Create tb_990EZ_return
CREATE TABLE tb_990EZ_return (
    OrgEin CHAR(9) REFERENCES tb_organization (OrgEin),
    ObjectId VARCHAR(22),
    ReturnDate date,
    ReturnType VARCHAR(5) CONSTRAINT r990ez_return_type_len_check CHECK (char_length(ReturnType) = 3 OR char_length(ReturnType) = 5),
    TaxYr CHAR(4) CONSTRAINT r990ez_tax_yr_len_check CHECK (char_length(TaxYr) = 4),
    GrossReceiptsAmt numeric,
    ContrGiftsGrantsEtcAmt numeric,
    ProgSrvcRevenueAmt numeric,
    MembershipDuesAmt numeric,
    TotalRevenueAmt numeric,
    FeesAndOtherPymtToIndCntrctAmt numeric,
    OtherExpnsTotalAmt numeric,
    TotalExpnsAmt numeric,
    ExcessOrDeficitForYearAmt numeric,
    NetAssetsOrFundBalancesBOYAmt numeric,
    OtherChangesInNetAssetsAmt numeric,
    NetAssetsOrFundBalancesEOYAmt numeric,
    CashSavingsAndInvestmentsBOYAmt numeric,
    CashSavingsAndInvestmentsEOYAmt numeric,
    OtherAssetsTotalDetailBOYAmt numeric,
    OtherAssetsTotalDetailEOYAmt numeric,
    Form990TotalAssetsBOYAmt numeric,
    Form990TotalAssetsEOYAmt numeric,
    SumOfTotalLiabilitiesBOYAmt numeric,
    SumOfTotalLiabilitiesEOYAmt numeric,
    NetAssetsOrFundBalancesGrpBOYAmt numeric,
    NetAssetsOrFundBalancesGrpEOYAmt numeric,
    TotalProgSrvcExpensesAmt numeric,
    CreateDate timestamp,
    isUpdated boolean DEFAULT FALSE,
    UpdateDate timestamp,
    UpdateBy CHAR(3),
    PRIMARY KEY (OrgEin, ObjectId, TaxYr)
);


-- Create tb_990PF_return
CREATE TABLE tb_990PF_return (
    OrgEin CHAR(9) REFERENCES tb_organization (OrgEin),
    ObjectId VARCHAR(22),
    ReturnDate date,
    ReturnType VARCHAR(5) CONSTRAINT r990pf_return_type_len_check CHECK (char_length(ReturnType) = 3 OR char_length(ReturnType) = 5),
    TaxYr CHAR(4) CONSTRAINT r990pf_tax_yr_len_check CHECK (char_length(TaxYr) = 4),
    FMVAssetsEOYAmt numeric,
    MethodOfAccountingCashInd CHAR(1),
    ContriRcvdRevAndExpnssAmt numeric,
    InterestOnSavRevAndExpnssAmt numeric,
    InterestOnSavNetInvstIncmAmt numeric,
    InterestOnSavingsAdjNetIncmAmt numeric,
    DividendsRevAndExpnssAmt numeric,
    DividendsNetInvstIncmAmt numeric,
    DividendsAdjNetIncmAmt numeric,
    GrossRentsRevAndExpnssAmt numeric,
    GrossRentsNetInvstIncmAmt numeric,
    GrossRentsAdjNetIncmAmt numeric,
    NetRentalIncomeOrLossAmt numeric,
    GrossSalesPriceAmt numeric,
    CapGainNetIncmNetInvstIncmAmt numeric,
    IncmModificationsAdjNetIncmAmt numeric,
    GrossSalesLessRetAndAllwncAmt numeric,
    CostOfGoodsSoldAmt numeric,
    GrossProfitAdjNetIncmAmt numeric,
    OtherIncomeNetInvstIncmAmt numeric,
    OtherIncomeAdjNetIncmAmt numeric,
    TotalRevAndExpnssAmt numeric,
    TotalNetInvstIncmAmt numeric,
    TotalAdjNetIncmAmt numeric,
    CreateDate timestamp,
    isUpdated boolean DEFAULT FALSE,
    UpdateDate timestamp,
    UpdateBy CHAR(3),
    PRIMARY KEY (OrgEin, ObjectId, TaxYr)
);